#!/usr/bin/env python3
"""Extract a 16x32 bitmap font from a PSF2 console font into a C header.

We do this at build time on the Mac rather than parsing the font on the phone.
That keeps the device binary self-contained: one static executable, no runtime
dependency on /usr/share/consolefonts, no gunzip, no PSF version guessing.

The phone already ships these fonts (they come with the kbd package, because
fbcon needs them). ter-232n.psf.gz is a 16 wide by 32 tall, 1 bit per pixel
font. 16x32 divides the 1080x1920 panel evenly:
    1080 / 16 = 67 columns
    1920 / 32 = 60 rows
so a terminal is a clean fit with no padding or clipping.

PSF2 header layout, all little-endian uint32:
     0  magic      0x864ab572
     4  version
     8  headersize  offset of the first glyph
    12  flags      bit 0 = a unicode table follows the glyphs
    16  length     number of glyphs
    20  charsize   bytes per glyph
    24  height     rows per glyph
    28  width      pixels per row

Glyphs are 1 bit per pixel, most significant bit leftmost, rows packed
consecutively with each row padded up to a whole number of bytes.
"""

import gzip
import struct
import sys

PSF2_MAGIC = 0x864AB572


def load_psf2(path):
    data = gzip.open(path, "rb").read()
    if len(data) < 32:
        raise SystemExit(f"{path}: too short to hold a PSF2 header")

    magic, version, headersize, flags, length, charsize, height, width = \
        struct.unpack("<8I", data[:32])

    if magic != PSF2_MAGIC:
        raise SystemExit(f"{path}: not PSF2 (magic {magic:#010x})")

    rowbytes = (width + 7) // 8
    need = rowbytes * height
    if charsize != need:
        raise SystemExit(
            f"{path}: charsize {charsize} disagrees with "
            f"{width}x{height} at 1bpp (expected {need}); "
            "this font is not a plain 1bpp bitmap")

    if headersize + length * charsize > len(data):
        raise SystemExit(f"{path}: truncated, want "
                         f"{headersize + length * charsize} bytes, have {len(data)}")

    return data, {
        "version": version,
        "headersize": headersize,
        "flags": flags,
        "length": length,
        "charsize": charsize,
        "height": height,
        "width": width,
    }


def render(data, hdr, code, col=0):
    """Return one glyph as a list of strings of '#' and '.', for eyeballing."""
    glyph, rowbytes = hdr["length"], (hdr["width"] + 7) // 8
    del glyph
    off = hdr["headersize"] + code * hdr["charsize"]
    rows = []
    for r in range(hdr["height"]):
        bits = ""
        for c in range(hdr["width"]):
            b = data[off + r * rowbytes + c // 8]
            bits += "#" if (b >> (7 - (c % 8))) & 1 else "."
        rows.append(bits)
    return rows


def emit(path, out, data, hdr):
    rowbytes = (hdr["width"] + 7) // 8
    off = hdr["headersize"]

    with open(out, "w") as f:
        f.write("/* Generated by mkfont.py. Do not edit. */\n")
        f.write(f"/* Source: {path} */\n")
        f.write(f"/* PSF2: {hdr['width']}x{hdr['height']}, "
                f"{hdr['length']} glyphs, {hdr['charsize']} bytes each, 1bpp */\n")
        f.write(f"#ifndef FONT_{hdr['width']}X{hdr['height']}_H\n")
        f.write(f"#define FONT_{hdr['width']}X{hdr['height']}_H\n\n")
        f.write(f"#define GLYPH_W {hdr['width']}\n")
        f.write(f"#define GLYPH_H {hdr['height']}\n")
        f.write(f"#define GLYPH_BYTES {rowbytes}\n")
        f.write(f"#define GLYPH_COUNT {hdr['length']}\n\n")
        f.write("static const unsigned char s5_font[GLYPH_COUNT][GLYPH_H * GLYPH_BYTES] = {\n")
        for g in range(hdr["length"]):
            base = off + g * hdr["charsize"]
            chunk = data[base:base + hdr["charsize"]]
            vals = ["0x%02x" % b for b in chunk]
            f.write("  { /* 0x%02x */ " % g)
            f.write(",".join(vals))
            f.write(" },\n")
        f.write("};\n\n#endif\n")


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "ter-232n.psf.gz"
    dst = sys.argv[2] if len(sys.argv) > 2 else "font16x32.h"

    data, hdr = load_psf2(src)
    print(f"{src}: {hdr['width']}x{hdr['height']} "
          f"{hdr['length']} glyphs, {hdr['charsize']} bytes each")

    for code, label in ((0x41, "A"), (0x42, "B"), (0x67, "g")):
        print(f"--- {label} (0x{code:02x}) ---")
        for r in render(data, hdr, code):
            print("  " + r)

    emit(src, dst, data, hdr)
    import os
    print(f"wrote {dst} ({os.path.getsize(dst)} bytes)")


if __name__ == "__main__":
    main()
