#!/usr/bin/env python3
"""Generate s5_font.h, the 5x7 glyph table used by s5screen.

The table is generated rather than hand-written on purpose: a transcribed
table is easy to corrupt silently, and a corrupted table looks like a broken
display rather than a broken build. Run this before compiling s5screen.

s5screen only prints upper-case ASCII plus space, so the table stays small,
which matters because it has to fit inside the BOOT initramfs. Glyphs are 5
wide by 7 tall and stored column-major, least significant bit = top pixel,
which is the layout s5screen.c reads.
"""

from pathlib import Path

# 5 columns x 7 rows, '#' = lit pixel.
GLYPHS = {
    " ": "..... ..... ..... ..... ..... ..... .....",
    "A": ".###. #...# #...# ##### #...# #...# #...#",
    "B": "####. #...# #...# ####. #...# #...# ####.",
    "C": ".###. #...# #.... #.... #.... #...# .###.",
    "D": "###.. #..#. #...# #...# #...# #..#. ###..",
    "E": "##### #.... #.... ####. #.... #.... #####",
    "F": "##### #.... #.... ####. #.... #.... #....",
    "G": ".###. #...# #.... #.### #...# #...# .###.",
    "H": "#...# #...# #...# ##### #...# #...# #...#",
    "I": "##### ..#.. ..#.. ..#.. ..#.. ..#.. #####",
    "J": "..### ...#. ...#. ...#. ...#. #..#. .##..",
    "K": "#...# #..#. #.#.. ##... #.#.. #..#. #...#",
    "L": "#.... #.... #.... #.... #.... #.... #####",
    "M": "#...# ##.## #.#.# #.#.# #...# #...# #...#",
    "N": "#...# ##..# #.#.# #..## #...# #...# #...#",
    "O": ".###. #...# #...# #...# #...# #...# .###.",
    "P": "####. #...# #...# ####. #.... #.... #....",
    "Q": ".###. #...# #...# #...# #.#.# #..#. .##.#",
    "R": "####. #...# #...# ####. #.#.. #..#. #...#",
    "S": ".#### #.... #.... .###. ....# ....# ####.",
    "T": "##### ..#.. ..#.. ..#.. ..#.. ..#.. ..#..",
    "U": "#...# #...# #...# #...# #...# #...# .###.",
    "V": "#...# #...# #...# #...# #...# .#.#. ..#..",
    "W": "#...# #...# #...# #.#.# #.#.# ##.## #...#",
    "X": "#...# #...# .#.#. ..#.. .#.#. #...# #...#",
    "Y": "#...# #...# .#.#. ..#.. ..#.. ..#.. ..#..",
    "Z": "##### ....# ...#. ..#.. .#... #.... #####",
    "0": ".###. #...# #..## #.#.# ##..# #...# .###.",
    "1": "..#.. .##.. ..#.. ..#.. ..#.. ..#.. .###.",
    "2": ".###. #...# ....# ...#. ..#.. .#... #####",
    "3": "##### ...#. ..#.. ...#. ....# #...# .###.",
    "4": "...#. ..##. .#.#. #..#. ##### ...#. ...#.",
    "5": "##### #.... ####. ....# ....# #...# .###.",
    "6": "..##. .#... #.... ####. #...# #...# .###.",
    "7": "##### ....# ...#. ..#.. .#... .#... .#...",
    "8": ".###. #...# #...# .###. #...# #...# .###.",
    "9": ".###. #...# #...# .#### ....# ...#. .##..",
    "-": "..... ..... ..... ##### ..... ..... .....",
    ".": "..... ..... ..... ..... ..... .##.. .##..",
    "!": "..#.. ..#.. ..#.. ..#.. ..#.. ..... ..#..",
    "?": ".###. #...# ....# ...#. ..#.. ..... ..#..",
    "/": "....# ...#. ...#. ..#.. .#... .#... #....",
    ":": "..... .##.. .##.. ..... .##.. .##.. .....",
    "+": "..... ..#.. ..#.. ##### ..#.. ..#.. .....",
}

WIDTH, HEIGHT, FIRST, LAST = 5, 7, 0x20, 0x5A


def columns(art):
    rows = art.split()
    assert len(rows) == HEIGHT, art
    assert all(len(r) == WIDTH for r in rows), art
    out = []
    for col in range(WIDTH):
        byte = sum(1 << r for r in range(HEIGHT) if rows[r][col] == "#")
        out.append(byte)
    return out


def main():
    table = []
    for code in range(FIRST, LAST + 1):
        table.extend(columns(GLYPHS.get(chr(code), GLYPHS["?"])))

    assert len(table) == 5 * (LAST - FIRST + 1), len(table)
    assert len(set(table)) > 20, "font looks degenerate"

    out = Path(__file__).with_name("s5_font.h")
    lines = [
        "/* Generated by font.py - do not edit by hand. */",
        "#ifndef S5_FONT_H",
        "#define S5_FONT_H",
        "",
        "#define S5_GLYPH_W %d" % WIDTH,
        "#define S5_GLYPH_H %d" % HEIGHT,
        "#define S5_FONT_FIRST 0x%02x" % FIRST,
        "#define S5_FONT_LAST 0x%02x" % LAST,
        "",
        "static const unsigned char s5_font[%d] = {" % len(table),
    ]
    for i in range(0, len(table), 12):
        lines.append("\t" + " ".join("0x%02x," % b for b in table[i : i + 12]))
    lines += ["};", "", "#endif /* S5_FONT_H */", ""]
    out.write_text("\n".join(lines))
    print(f"wrote {out} ({len(table)} bytes, chars 0x{FIRST:02x}..0x{LAST:02x})")

    # Self-check: round-trip every glyph back out of the byte table and
    # confirm it still matches the art, so a generation bug cannot slip past.
    for code in range(FIRST, LAST + 1):
        art = GLYPHS.get(chr(code), GLYPHS["?"])
        back = columns(art)
        got = table[(code - FIRST) * 5 : (code - FIRST) * 5 + 5]
        assert back == got, f"round-trip failed for {chr(code)!r}"
    print("round-trip self-check passed for all %d glyphs" % (LAST - FIRST + 1))


if __name__ == "__main__":
    main()
